import type {Metadata} from "next"
import {Inter} from "next/font/google"
import "./globals.css"

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <nav className="fixed justify-between items-center top-0 py-3 px-10 left-0 right-0 flex bg-primary z-10 text-white">
          <h1 className="text-3xl font-semibold">Octa Coffee</h1>
          <div>
            <ul className="flex gap-x-10">
              <li>Home</li>
              <li>Menu</li>
              <li>Our</li>
              <li>Store</li>
            </ul>
          </div>
          <button className="bg-secondary px-7 rounded-sm py-1">Login</button>
        </nav>
        {children}
      </body>
    </html>
  )
}
